TicketSystem/TicketSystem/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('Tickets/', include('Tickets.urls', namespace='Tickets')),
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
]

TicketSystem/Tickets/urls.py
from django.urls import path
from . import views

app_name = 'Tickets'

urlpatterns = [
    path('<username>', views.TicketList.as_view(), name='all'),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
    path('new/', views.CreateTicket.as_view(), name='create'),
    path('<username>/<int:pk>/', views.TicketDetail.as_view(), name='single'),
    path('<username>/<int:pk>/update/', views.TicketUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', views.TicketDelete.as_view(), name='delete'),
]

TicketSystem/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
]

TicketSystem/Tickets/models.py
from django.db import models
from datetime import datetime
from django.urls import reverse

from django.contrib.auth import get_user_model
User = get_user_model()


# Create your models here.

class Ticket(models.Model):
    user = models.ForeignKey(User, related_name="tickets", on_delete=models.CASCADE)
    title = models.CharField("Title", max_length=100)
    submissionDate = models.DateTimeField("Date Submitted", auto_now=True)
    description = models.TextField("Description")
    highPriority = models.BooleanField("High Priority", default=None, help_text="Is this issue urgent?")

    class Meta:
        ordering = ["-submissionDate"]
        unique_together = ["user", "title"]     # Consider removing so someone can use the same name for a ticket

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "Tickets:single", 
            kwargs={
                "pk":self.pk,
                "user":self.user,
                "username":self.user.username
            }
        )
    
    # Provided by shacker on Stackoverflow
    def get_fields(self):
        """Returns a list of all field names on the instance."""
        fields = []
        for field in self._meta.fields:
            field_name = field.name        
            # resolve picklists/choices, with get_xyz_display() function
            get_choice = "get_"+field_name+"_display"
            if hasattr(self, get_choice):
                value = getattr(self, get_choice)()
            else:
                try:
                    value = getattr(self, field_name)
                except AttributeError:
                    value = None

            # only display fields with values and skip some fields entirely
            if value and field_name not in ("id") :

                fields.append(
                {
                    "label":field.verbose_name, 
                    "name":field.name, 
                    "value":value,
                }
                )
        return fields

TicketSystem/accounts/models.py
from django.db import models
from django.contrib.auth import models

# Create your models here.

class User(models.User, models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

TicketSystem/Tickets/forms.py
from django import forms
from . import models

class TicketForm(forms.ModelForm):
    class Meta:
        model = models.Ticket
        fields = (
            "title",
            "description",
            "highPriority"
        )

TicketSystem/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


# Create forms here.

class UserSignUpForm(UserCreationForm):

    class Meta:
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')
        model = get_user_model()

    # Creating label for fields
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email Address'
        

TicketSystem/TicketSystem/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView


class TestPage(TemplateView):
    template_name = 'test.html'

class ThanksPage(TemplateView):
    template_name = 'thanks.html'

class HomePage(TemplateView):
    template_name = 'index.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse("test"))
        return super().get(request, *args, **kwargs)

TicketSystem/Tickets/views.py
from django.db import models
from django.http import Http404
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404

from .forms import TicketForm
from .models import Ticket

from django.contrib.auth import get_user_model
User = get_user_model()


# Create your views here.

class Dashboard(LoginRequiredMixin, generic.ListView):
    model = Ticket
    template_name = "Tickets/ticket_dashboard.html"

class CreateTicket(LoginRequiredMixin, generic.CreateView):
    # Use this for more complicated forms: explicit call
    form_class = TicketForm
    # Use this for basic forms: Django automatically created model form from model
    # model = models.Ticket
    # fields = ("title", "description", "highPriority")
    template_name = "Tickets/ticket_form.html"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class TicketList(LoginRequiredMixin, generic.ListView):
    model = Ticket
    template_name = "Tickets/ticket_list.html"

    def get_queryset(self):
        self.user.username = get_object_or_404(Ticket, user=self.kwargs['user'])
        return Ticket.objects.filter(user=self.user)

    def get_context_data(self):
        context = super().get_context_data(**kwargs)
        context["user"] = self.user
        return context

    # def get_queryset(self):
    #     try:
    #         user_tickets = Ticket.objects.filter(self.user="username")
    #     except User.DoesNotExist:
    #         raise Http404
    #     else:
    #         return user_tickets

    #     def get_context_data(self, **kwargs):
    #         context = super().get_context_data(**kwargs)
    #         context["Ticket_user"] = user_tickets
    #         return context

    # def get_queryset(self):
    #     try:
    #         self.ticket_user = User.objects.prefetch_related("tickets").get(
    #             username__iexact=self.kwargs.get("username")
    #         )
    #     except User.DoesNotExist:
    #         raise Http404
    #     else:
    #         return self.ticket_user.tickets.all()

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context["ticket_user"] = self.ticket_user
    #     return context

class TicketDetail(LoginRequiredMixin, generic.DetailView):
    model = Ticket
    template_name = "Tickets/ticket_detail.html"

class TicketUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Ticket
    fields = ["title","description","highPriority"]
    template_name = "Tickets/ticket_update.html"

    def get_success_url(self):
        return reverse_lazy("Tickets:all")

class TicketDelete(LoginRequiredMixin, generic.DeleteView):
    model = Ticket
    success_url = reverse_lazy("Tickets:all")

TicketSystem/accounts/views.py
from django.contrib.auth import login, logout
from django.urls import reverse_lazy
from django.views.generic import CreateView

from . import forms

# Create your views here.

class SignUp(CreateView):
    form_class = forms.UserSignUpForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

TicketSystem/Tickets/templates/Tickets/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Basic ticketing system">
    <meta name="author" content="Zachary">
    <title>Ticket System</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "Tickets/css/style.css" %}"/>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <main role="main" class="container">

      {% block content %}
      {% endblock %}
    </main>

    <footer class="container">
      <p>&copy; Company 2017-2020</p>
    </footer>

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

  </body>
</html>

TicketSystem/Tickets/templates/Tickets/ticket_base.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="row">
    {% block preticket %}{% endblock %}
    {% block ticket_content %}{% endblock %}
    {% block postticket %}{% endblock %}
  </div>
</div>
{% endblock %}

TicketSystem/Tickets/templates/Tickets/ticket_dashboard.html
{% extends "Tickets/ticket_base.html" %}

{% block preticket %}
    <div class="d-flex w-100 justify-content-between">
        <div class="content">
            <h3>Welcome to the Tickets Page!</h3>
            <h5 class="text-muted">Select a ticket to view.</h5>
        </div>
        <a href="{% url 'Tickets:create' %}" class="mdc-fab mdc-fab--extended" role="button">
            <div class="mdc-fab__ripple"></div>
            <span class="material-icons mdc-fab__icon">add_circle</span>
            <span class="mdc-fab__label">New Ticket</span>
        </a>
    </div>
{% endblock %}

{% block ticket_content %}
        <div class="list-group my-4">
            {% for ticket in ticket_list %}
            <a href="{% url 'Tickets:single' pk=ticket.pk %}" class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-between">
                    <h3 class="mb-1">{{ ticket.title }}</h3>
                    <small class="text-muted">{{ ticket.submissionDate }}</small>
                </div>
                <small class="text-muted">{{ ticket.description }}</small>
            </a>
            {% endfor %}
        </div>
{% endblock %}

TicketSystem/Tickets/templates/Tickets/ticket_delete.html
<form method="POST" action="{% url 'Tickets:delete' pk=ticket.pk %}" id="delete" class="ml-auto">
    {% csrf_token %}
    <button type="submit" form="delete" class="mdc-fab mdc-fab--extended">
        <div class="mdc-fab__ripple"></div>
        <span class="material-icons mdc-fab__icon">delete_outline</span>
        <span class="mdc-fab__label">Delete</span>
    </button>
</form>

TicketSystem/Tickets/templates/Tickets/ticket_detail.html
{% extends "Tickets/ticket_base.html" %}
{% load bootstrap4 %}

{% block preticket %}
    <div class="d-flex w-100 justify-content-between">
        <div class="content">
            <h3>Ticket Details</h3>
        </div>
        <a href="{% url 'Tickets:update' pk=ticket.pk %}" class="mdc-fab mdc-fab--extended" role="button">
            <div class="mdc-fab__ripple"></div>
            <span class="material-icons mdc-fab__icon">edit</span>
            <span class="mdc-fab__label">Edit</span>
        </a>
    </div>
{% endblock %}

{% block ticket_content %}
    <table class="table table-hover my-4">
        {% for field in ticket.get_fields %}
            <tr>
                <th>{{ field.label }}</th>
                <td>{{ field.value }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

{% block postticket %}
    {% include 'Tickets/ticket_delete.html' %}
{% endblock %}
    

TicketSystem/Tickets/templates/Tickets/ticket_form.html
{% extends 'Tickets/ticket_base.html' %}
{% load bootstrap4 %}

{% block preticket %}
    <h1>@{{ user.username }}</h1>
{% endblock %}
{% block ticket_content %}
    <div class="container">
        <h3>Create A New Ticket</h3>
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary btn-large">Create</button>
            {% endbuttons %}
        </form>
    </div>
{% endblock %}

TicketSystem/Tickets/templates/Tickets/ticket_list.html
{% extends "Tickets/ticket_base.html" %}

{% block preticket %}
    <div class="d-flex w-100 justify-content-between">
        <div class="content">
            <h3>@{{ user.username }} Tickets</h3>
            <h5 class="text-muted">Select a ticket to view.</h5>
        </div>
        <a href="{% url 'Tickets:create' %}" class="mdc-fab mdc-fab--extended" role="button">
            <div class="mdc-fab__ripple"></div>
            <span class="material-icons mdc-fab__icon">add_circle</span>
            <span class="mdc-fab__label">New Ticket</span>
        </a>
    </div>
{% endblock %}

{% block ticket_content %}
    <div class="container">
        <div class="list-group my-4">
            {% for ticket in ticket_list %}
                <a href="{% url 'Tickets:single' pk=ticket.pk %}" id="ticket-list" class="list-group-item list-group-item-action flex-column align-items-start">
                    <div class="d-flex w-100 justify-content-between">
                        <h3 class="mb-1">{{ ticket.title }}</h3>
                        <small class="text-muted">{{ ticket.submissionDate }}</small>
                    </div>
                    <small id="ticket-description" class="text-muted">{{ ticket.description }}</small>
                </a>
            {% endfor %}
        </div>
    </div>    
{% endblock %}

TicketSystem/Tickets/templates/Tickets/ticket_update.html
{% extends 'Tickets/ticket_base.html' %}
{% load bootstrap4 %}

{% block ticket_content %}
    <div class="container">
        <h3>Edit Ticket: {{ticket_detail_update.title}}</h3>
        <form method="POST" action="{% url 'Tickets:update' pk=ticket.pk %}" id="update" class="my-4">
          {% csrf_token %}
          {% bootstrap_form form %}
        </form>
        <div class="float-right">
          <a href="{% url 'Tickets:all' %}" role="button" class="mdc-fab mdc-fab--extended" id="cancel_button">
            <div class="mdc-fab__ripple"></div>
            <span class="material-icons mdc-fab__icon">clear</span>
            <span class="mdc-fab__label">Cancel</span>
          </a>
          <button type="submit" form="update" class="mdc-fab mdc-fab--extended">
            <div class="mdc-fab__ripple"></div>
            <span class="material-icons mdc-fab__icon">done</span>
            <span class="mdc-fab__label">Save</span>
          </button>
        </div>
    </div>
{% endblock %}

TicketSystem/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
    <div class="container">
        <h3>Login</h3>
        <form method="POST" id="login">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" form="login" class="mdc-fab mdc-fab--extended">
                <div class="mdc-fab__ripple"></div>
                <span class="material-icons mdc-fab__icon">input</span>
                <span class="mdc-fab__label">Log In</span>
            </button>
        </form>
    </div>
{% endblock %}

TicketSystem/accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
    <div class="container">
        <h3>Sign Up</h3>
        <form method="POST" id="signup">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" form="signup" class="mdc-fab mdc-fab--extended">
                <div class="mdc-fab__ripple"></div>
                <span class="material-icons mdc-fab__icon">input</span>
                <span class="mdc-fab__label">Create User</span>
            </button>
        </form>
    </div>
{% endblock %}

TicketSystem/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <!-- Google's material icons -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <!-- Google's material stylesheet -->
        <link rel="stylesheet" href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css">
        <!-- Custom stylesheet -->
        <link rel="stylesheet" href="{% static 'css/master.css' %}">

        <title>Ticket System</title>
        <meta name="description" content="Basic ticketing system">
        <meta name="author" content="Zachary">
    </head>
    <body class="d-flex flex-column h-100">
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark shadow mb-3 p-2">
                <a href="{% url 'home' %}" class="navbar-brand mdc-fab" role="button">
                    <div class="mdc-fab__ripple"></div>
                    <span class="material-icons mdc-fab__icon">home</span>
                </a>
                <h3 class="navbar-brand">Ticket System</h3>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse container" id="navbarSupportedContent">
                    <div class="navbar-nav ml-auto">
                        {% if user.is_authenticated %}
                            <a class="nav-item nav-link" href="{% url 'Tickets:dashboard' %}">Dashboard</a>
                            <a class="nav-item nav-link" href="{% url 'Tickets:create' %}">Submit Ticket</a>
                            <a class="nav-item nav-link" href="{% url 'Tickets:all' %}">View Tickets</a>
                            <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                        {% else %}
                            <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a>
                            <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
                            <a class="nav-item nav-link" href="{% url 'Tickets:all' %}">Employee Portal</a>
                        {% endif %}  
                    </div>
                </div>
            </nav>
        </header>
        
        <main role="main" class="my-5 py-5">
            <div class="container test">
                {% block content %}
                {% endblock %}
            </div>
        </main>

        <footer class="footer sticky-bottom py-3">
            <div class="container">
                <span class="text-muted">Place sticky footer content here.</span>
            </div>
        </footer>

        <!-- Import project javascript file -->
        <script src="{% static 'js/master.js' %}" type="text/javascript"></script>
        <!-- Import Material Jabascript file -->
        <!-- <script src="bundle.js" async></script> -->
        <!-- jQuery and Bootstrap Bundle (includes Popper) -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    </body>
</html>

TicketSystem/templates/index.html
{% extends "base.html" %}
{% block content %}

    <h1>Welcome to my Ticket System</h1>

{% endblock %}

TicketSystem/templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>You are now logged in!</h1>
</div>

{% endblock %}

TicketSystem/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}